// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChdpnn-XTwDNwrvj9WmgHoIlT_iuEiIcc',
    appId: '1:963383330656:web:630b64a24cdee5d838c005',
    messagingSenderId: '963383330656',
    projectId: 'welink-343815',
    authDomain: 'welink-343815.firebaseapp.com',
    storageBucket: 'welink-343815.appspot.com',
    measurementId: 'G-WCTFMZES7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGRo1vBlpw2IECPZP4htCaM3Eq3a1Cjoo',
    appId: '1:963383330656:android:594d7f7d2c6fa51a38c005',
    messagingSenderId: '963383330656',
    projectId: 'welink-343815',
    storageBucket: 'welink-343815.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5MeYzudFkV428bCMxu2hBDO4t5j4pyqA',
    appId: '1:963383330656:ios:d9ba9f0447a38cea38c005',
    messagingSenderId: '963383330656',
    projectId: 'welink-343815',
    storageBucket: 'welink-343815.appspot.com',
    androidClientId: '963383330656-1pfkmei165f93kdh3a927to392pit7d1.apps.googleusercontent.com',
    iosClientId: '963383330656-n0aj3j1at0iu5431qv41t892bev8plfo.apps.googleusercontent.com',
    iosBundleId: 'com.welink.user',
  );
}
